component TabItem inherits Rectangle {
    in property <string> title;
    in property <int> index;
    in property <bool> active;

    callback select();
    callback close();

    width: 280px;
    height: 40px;
    background: active ? #f4f5f9 : #ffffff;

    TouchArea {
        clicked => {
            root.select();
        }
    }

    HorizontalLayout {
        Text {
            text: title;
            horizontal-stretch: 1;
        }

        Rectangle {
            Text {
                text: "x";
            }

            TouchArea {
                clicked => { root.close() }
            }
        }
    }
}

export component AppWindow inherits Window {
    width: 1200px;
    height: 800px;
    background: white;

    in-out property <[string]> tabs;
    in-out property <int> active-tab: 0;

    callback add-tab();
    callback select-tab(int);
    callback close-tab(int);

    HorizontalLayout {
        spacing: 0px;

        VerticalLayout {
            for tab[index] in tabs: TabItem {
                title: tab;
                index: index;
                active: index == active-tab;
                select => {
                    root.select-tab(index);
                }
                close => {
                    root.close-tab(index);
                }
            }

            Rectangle {
                width: 280px;
                height: 40px;
                background: #f4f5f9;

                Text {
                    text: "+";
                }

                TouchArea {
                    clicked => {
                        root.add-tab()
                    }
                }
            }
        }
    }
}
